### ISSUE TITLE
Does not work anymore :(

### ISSUE THREAD

**Issue by seriouz** [ComputerScienceHouse/gitlab-ce-oidc#1]
The docker image does not work anymore. Gitlab won't compile, because the gem "omniauth-openid-connect" is missing.
@stevenmirabito

**Comment by stevenmirabito** [comment]
Fixed with https://github.com/ComputerScienceHouse/gitlab-ce-oidc/commit/1b365defc23903e1d3dc9e1c6193d0af99cc10b3, thanks for the heads up!
